name: Test Deploy Notify

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  fake-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Simulate deploy
        run: |
          echo "Pretending to build & deploy image..."
          sleep 2
          echo "Deploy done ✅"

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C0B9UP5L92B'
          payload: |
            {
              "text": "🚀 *${{ github.repository }}* deployed\nPR: \"${{ github.event.pull_request.title }}\" by ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
