name: Test Deploy Notify
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  fake-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Simulate deploy
        run: |
          echo "Pretending to build & deploy image..."
          sleep 2
          echo "Deploy done ✅"

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C0B9UP5L92B'
          payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "blocks": [
                    {
                      "type": "section",
                      "text": { "type": "mrkdwn", "text": "<!channel>" }
                    },
                    {
                      "type": "header",
                      "text": { "type": "plain_text", "text": "🚀 Deployment Successful" }
                    },
                    {
                      "type": "section",
                      "fields": [
                        { "type": "mrkdwn", "text": "*Repo:*\n${{ github.repository }}" },
                        { "type": "mrkdwn", "text": "*Author:*\n${{ github.event.pull_request.user.login }}" },
                        { "type": "mrkdwn", "text": "*PR:*\n${{ github.event.pull_request.title }}" },
                        { "type": "mrkdwn", "text": "*Branch:*\nstaging" }
                      ]
                    },
                    {
                      "type": "section",
                      "text": { "type": "mrkdwn", "text": "<${{ github.event.pull_request.html_url }}|View Pull Request>" }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
